name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
          --build-arg VITE_SERVER_BASE_URL=${{ secrets.VITE_SERVER_BASE_URL }} \
          --build-arg VITE_REACT_BASE_URL=${{ secrets.VITE_REACT_BASE_URL }} \
          -t muhammadyusuf2766/gssiotfigma-react .

      - name: Publish Image to Docker Hub
        run: docker push muhammadyusuf2766/gssiotfigma-react:latest
      - name: Remove unused Docker images
        run: docker system prune -af

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull muhammadyusuf2766/gssiotfigma-react:latest

      - name: Delete old container
        run: docker rm -f reactjs-app-container

      - name: Run Docker Container
        run: docker run -d -p 3001:80 --name reactjs-app-container muhammadyusuf2766/gssiotfigma-react
